# Generated by Django 3.0.3 on 2020-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200223_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='nickname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
