# Generated by Django 3.0.3 on 2020-02-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
