# Generated by Django 3.0.3 on 2020-02-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='session_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
