# Generated by Django 3.0.4 on 2020-03-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200309_1621'),
        ('carts', '0010_auto_20200309_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='products.Variation'),
        ),
    ]
