# Generated by Django 3.0.3 on 2020-02-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_address_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='ADDRESS_TYPES',
            new_name='address_type',
        ),
    ]
