# Generated by Django 3.0.3 on 2020-02-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20200218_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='n', max_length=120),
            preserve_default=False,
        ),
    ]
