# Generated by Django 3.0.4 on 2020-03-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
