# Generated by Django 3.0.3 on 2020-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20200225_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='code_400',
            field=models.NullBooleanField(),
        ),
    ]
