# Generated by Django 3.0.3 on 2020-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_marketingpreference_code_400_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
