# Generated by Django 3.0.3 on 2020-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_marketingpreference_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
