# Generated by Django 3.0.3 on 2020-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_marketingpreference_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='code_400',
            field=models.NullBooleanField(default=False),
        ),
    ]
